# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c4bdd388f250ff4e596d43d9a6a47af2707d66a06ff397778470dd09edbd85bbbeb3fe93a9ecbad4208090acc48580c2454cd671a23ffd3f221fd467405cf82

test:
  secret_key_base: ac094734e0520e40c770ba9529f759edce0192817c9944ef834149db4ac55c73a9b21a37045bbad86ba2d593ddc6a98b12f8d57f8fa087eace269feaf67cfe76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
